# Generated by Django 6.0.3 on 2026-03-26 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='password',
            field=models.CharField(blank=True, max_length=8, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
